@echo OFF
ECHO Activating Conda environment...
call C:\ProgramData\anaconda3\Scripts\activate.bat C:\Users\Dilasa-AI\.conda\envs\anythingllm
ECHO Starting all services with yarn dev:all...
yarn dev:all